name: cupertino_stepper
description: >-
  Stepper is a widget that displays progress through a sequence of steps. This is a Cupertino
  version of the stock Material Stepper in Flutter.
version: 0.2.1
homepage: https://github.com/jpnurmi/cupertino_stepper
repository: https://github.com/jpnurmi/cupertino_stepper
issue_tracker: https://github.com/jpnurmi/cupertino_stepper/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  flutter_svg: '^2.0.9'
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
